

import java.io.File;
import java.io.IOException;

public class MainClass {

	private static Mancala mancalaGame;
	private static MancalaView mancalaView;
	private static MancalaController mancalaController;
	
	/**
	 * Main class for executing game and giving list of files to be loaded into memory for further usage
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		String[] files = 
		{
			"background.png",
			"create_host.png",
			"create_host_active.png",
			"exit.png",
			"exit_active.png",
			"history_of_games.png",
			"history_of_games_active.png",
			"hot_seat.png",
			"hot_seat_active.png",
			"join_server.png",
			"join_server_active.png",
			"menu_background.png",
			"pit.png",
			"seed.png",
			"store.png",
			"pit_active.png"
		};
		// check, if files exists
		for(int i = 0; i < files.length; i++){
			File dir = new File(getCurrentDirectory() + "pic/" + files[i]);
			if(!dir.isFile()){
				System.err.println("File '" + files[i] + "' is missing in directory " + 
						"'" + getCurrentDirectory() + "pic/'");
				System.exit(-1);
			}
			files[i] = getCurrentDirectory() + "pic/" + files[i];
		}
		
		// generate game model (Mancala is generated by Fujaba)
		mancalaGame = new Mancala();
		// generate view with Swing JFrame for showing game state and menu
		mancalaView = new MancalaView(mancalaGame, files);
		// logic for mouse clicks in Swing JFrame
		mancalaController = new MancalaController(mancalaGame, mancalaView);
		

	}
	
	/**
	 * Gets directory location where main .jar files is located
	 * 
	 * @return full path of current location
	 */
	public static String getCurrentDirectory(){
		File dir = new File (".");
		try {
			return dir.getCanonicalPath() + "/";
		} catch (IOException e) {
			return null;
		}
	}

}
