/*
 * generated by Fujaba - CodeGen2
 */
package esimenePakk;
import de.uni_kassel.features.annotation.util.Property; // requires Fujaba5/libs/features.jar in classpath
import de.uni_kassel.features.ReferenceHandler; // requires Fujaba5/libs/features.jar in classpath


public class Deck
{



   public static final String PROPERTY_NO_OF_CARDS = "NoOfCards";

   @Property( name = PROPERTY_NO_OF_CARDS, kind = ReferenceHandler.ReferenceKind.ATTRIBUTE )
   private int NoOfCards;

   @Property( name = PROPERTY_NO_OF_CARDS )
   public void setNoOfCards (int value)
   {
      this.NoOfCards = value;
   }

   public Deck withNoOfCards (int value)
   {
      setNoOfCards (value);
      return this;
   }

   @Property( name = PROPERTY_NO_OF_CARDS )
   public int getNoOfCards ()
   {
      return this.NoOfCards;
   }

   /**
    * <pre>
    *           0..1     taken from deck     0..1
    * Deck ------------------------- Card
    *           taken from deck               card
    * </pre>
    */
   public static final String PROPERTY_CARD = "card";

   @Property( name = PROPERTY_CARD, partner = Card.PROPERTY_TAKEN FROM DECK, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card card;

   @Property( name = PROPERTY_CARD )
   public boolean setCard (Card value)
   {
      boolean changed = false;

      if (this.card != value)
      {
      
         Card oldValue = this.card;
         Deck source = this;
         if (this.card != null)
         {
            this.card = null;
            oldValue.setTaken from deck (null);
         }
         this.card = value;

         if (value != null)
         {
            value.setTaken from deck (this);
         }
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_CARD )
   public Deck withCard (Card value)
   {
      setCard (value);
      return this;
   }

   public Card getCard ()
   {
      return this.card;
   }

   /**
    * <pre>
    *           0..1     has Deck of Cards     0..1
    * Deck ------------------------- MauMau
    *           deck               mauMau
    * </pre>
    */
   public static final String PROPERTY_MAU_MAU = "mauMau";

   @Property( name = PROPERTY_MAU_MAU, partner = MauMau.PROPERTY_DECK, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private MauMau mauMau;

   @Property( name = PROPERTY_MAU_MAU )
   public boolean setMauMau (MauMau value)
   {
      boolean changed = false;

      if (this.mauMau != value)
      {
      
         MauMau oldValue = this.mauMau;
         Deck source = this;
         if (this.mauMau != null)
         {
            this.mauMau = null;
            oldValue.setDeck (null);
         }
         this.mauMau = value;

         if (value != null)
         {
            value.setDeck (this);
         }
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_MAU_MAU )
   public Deck withMauMau (MauMau value)
   {
      setMauMau (value);
      return this;
   }

   public MauMau getMauMau ()
   {
      return this.mauMau;
   }

   public void removeYou()
   {
      this.setCard (null);
      this.setMauMau (null);
   }
}


