/*
 * generated by Fujaba - CodeGen2
 */
package esimenePakk;
import de.uni_kassel.features.annotation.util.Property; // requires Fujaba5/libs/features.jar in classpath
import de.uni_kassel.features.ReferenceHandler; // requires Fujaba5/libs/features.jar in classpath


public class Player
{



   public static final String PROPERTY_DEALER = "Dealer";

   @Property( name = PROPERTY_DEALER, kind = ReferenceHandler.ReferenceKind.ATTRIBUTE )
   private boolean Dealer;

   @Property( name = PROPERTY_DEALER )
   public void setDealer (boolean value)
   {
      this.Dealer = value;
   }

   public Player withDealer (boolean value)
   {
      setDealer (value);
      return this;
   }

   @Property( name = PROPERTY_DEALER )
   public boolean isDealer ()
   {
      return this.Dealer;
   }

   public static final String PROPERTY_NAME = "Name";

   @Property( name = PROPERTY_NAME, kind = ReferenceHandler.ReferenceKind.ATTRIBUTE )
   private String Name;

   @Property( name = PROPERTY_NAME )
   public void setName (String value)
   {
      this.Name = value;
   }

   public Player withName (String value)
   {
      setName (value);
      return this;
   }

   @Property( name = PROPERTY_NAME )
   public String getName ()
   {
      return this.Name;
   }

   /**
    * <pre>
    *           0..n     plays     0..1
    * Player ------------------------- MauMau
    *           player               mauMau
    * </pre>
    */
   public static final String PROPERTY_MAU_MAU = "mauMau";

   @Property( name = PROPERTY_MAU_MAU, partner = MauMau.PROPERTY_PLAYER, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private MauMau mauMau;

   @Property( name = PROPERTY_MAU_MAU )
   public boolean setMauMau (MauMau value)
   {
      boolean changed = false;

      if (this.mauMau != value)
      {
      
         MauMau oldValue = this.mauMau;
         Player source = this;
         if (this.mauMau != null)
         {
            this.mauMau = null;
            oldValue.removeFromPlayer (this);
         }
         this.mauMau = value;

         if (value != null)
         {
            value.addToPlayer (this);
         }
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_MAU_MAU )
   public Player withMauMau (MauMau value)
   {
      setMauMau (value);
      return this;
   }

   public MauMau getMauMau ()
   {
      return this.mauMau;
   }

   public void removeYou()
   {
      this.setMauMau (null);
   }
}


