/*
 * generated by Fujaba - CodeGen2
 */
package FileSystem;
import de.uni_kassel.features.annotation.util.Property; // requires Fujaba5/libs/features.jar in classpath
import de.uni_kassel.features.ReferenceHandler; // requires Fujaba5/libs/features.jar in classpath


public class Root extends AbstractFile
{



   private  Root ()
   {
   }

   public Root getInstance ()
   {
      boolean fujaba__Success = false;

      return this.root;
   }

   public static final String PROPERTY_ROOT = "root";

   @Property( name = PROPERTY_ROOT, kind = ReferenceHandler.ReferenceKind.ATTRIBUTE )
   private static Root root;

   @Property( name = PROPERTY_ROOT )
   private static void setRoot (Root value)
   {
      Root.root = value;
   }


   @Property( name = PROPERTY_ROOT )
   private static Root getRoot ()
   {
      return Root.root;
   }

}


