/*
 * generated by Fujaba - CodeGen2
 */
package FileSystem;
import java.util.ArrayList;
import java.util.Iterator;

import de.uni_kassel.features.annotation.util.Property; // requires Fujaba5/libs/features.jar in classpath
import de.uni_kassel.features.ReferenceHandler; // requires Fujaba5/libs/features.jar in classpath


public class SearchVisitor extends Visitor
{
   private ArrayList<String> namesArray = new ArrayList<String>();
   
   public static final String PROPERTY_SEARCH_PATTERN = "searchPattern";

   @Property( name = PROPERTY_SEARCH_PATTERN, kind = ReferenceHandler.ReferenceKind.ATTRIBUTE )
   private String searchPattern;

   @Property( name = PROPERTY_SEARCH_PATTERN )
   public void setSearchPattern (String value)
   {
      this.searchPattern = value;
   }

   public SearchVisitor withSearchPattern (String value)
   {
      setSearchPattern (value);
      return this;
   }

   @Property( name = PROPERTY_SEARCH_PATTERN )
   public String getSearchPattern ()
   {
      return this.searchPattern;
   }

   public void visit (Directory directory )
   {
	   namesArray.clear();
	   Iterator<? extends AbstractFile> I= directory.iteratorOfAbstractFile();
	   while(I.hasNext()){
		   RegularFile af = (RegularFile)I.next();
		   namesArray.add(af.getName());
	   }
	   return ;
   }

   public void visit (RegularFile file )
   {
	   namesArray.clear();
	   namesArray.add(file.getName());
   }

   public String findAll ()
   {
	   String s = "";
	   Iterator<String> i = namesArray.iterator();
	   while(i.hasNext()) s = s + i.next()+"\n";
	   return s;
   }
   
   public String findAll (String ext)
   {
	   String s = "";
	   Iterator<String> i = namesArray.iterator();
	   while(i.hasNext()){ 
		   String c = i.next();
		   if(c.endsWith("."+ext))s = s + c +"\n";
	   }
	   return s;
   }
}


