/*
 * generated by Fujaba - CodeGen2
 */
package FileSystem;


public class Visitor
{



   public void visit (Directory directory )
   {
   }

   public void visit (RegularFile file )
   {
   }

   public void removeYou()
   {
   }
}


